Python backend building with scikit-build
commit 8c7d0bcc7ef5377912f9fdbe6984b6d66f910589
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 20:48:33 2025 -0500

    Need tests for de440

commit c527b4d097519a02ab05c9010938609b09ada0c2
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 20:39:30 2025 -0500

    Disable macos until os version issue can be addressed

      delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.15:
      /private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/tmpia6jo5_4/wheel/pyoorb.dylibs/libquadmath.0.dylib has a minimum target of 15.0
      /private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/tmpia6jo5_4/wheel/pyoorb.dylibs/libgcc_s.1.1.dylib has a minimum target of 11.0
      /private/var/folders/kk/yc0qf4694xl1_d6sqg40_2sr0000gn/T/tmpia6jo5_4/wheel/pyoorb.dylibs/libgfortran.5.dylib has a minimum target of 15.0
      Set the environment variable 'MACOSX_DEPLOYMENT_TARGET=15.0' to update minimum supported macOS for this wheel.

commit 8a588e6adb81bba24a5eec3427601db6b129fb4d
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 20:34:47 2025 -0500

    macos-latest failed in delocate step

commit eba896bf2dc1f060e3b68c998efbbfcc16038977
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 20:16:23 2025 -0500

    macos-13 is apparently retired

commit 6e059cc923bbba9d255ee2b9b8fed458fad74d0b
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 20:15:09 2025 -0500

    Simplify architectures and fix(?) restoring data cache

commit 5abc2b63b1b0e11cf5a47e358c550f6a51d0764c
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 20:08:37 2025 -0500

    Fix typo

commit 96230c482a8b931cce0e553ce8bf7de30bedbb56
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 19:51:07 2025 -0500

    Fix oorb_data caching

commit 41f6e254c44acc95611441cf7f55951b5b05ca0e
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 17:06:48 2025 -0500

    Try to fix gh actions cache fail

commit 1263bf3a0237333e13e9bfb6d8d96bd5fb0d2e21
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:53:49 2025 -0500

    skip musllinux for now

commit 653b6320e580a7dd5d5207731289493ad9e4e4d4
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:41:11 2025 -0500

    Test built wheels

commit a8642e2195f800e6ba96e883a3d5cf9d18d2cd04
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:31:48 2025 -0500

    Clean up

commit 68edac1aee33f6928859d7cbb7f6e22c2cd96b75
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:30:57 2025 -0500

    Fix working directory

commit 2e892c107c4bd3d7a357dba5654a0f30ee8e11ac
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:27:03 2025 -0500

    Try recent ninja

commit 3ee24d76421d08ac548d12b5152a39e3c489b981
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:24:04 2025 -0500

    clean up

commit 077f8ff19417ce5c72047215602c584a72c4c75d
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:20:03 2025 -0500

    Clean up pyproject

commit 628dc76938e71259de5aa512dd2d5d7c5a021fa4
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:18:16 2025 -0500

    Building with pypa build

commit f33fa569f49b56125609a051ce54abe9d8163490
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 16:05:16 2025 -0500

    u

commit 858e846aff82752c761da2b88b497063a7083ea5
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 15:12:38 2025 -0500

    Builds with cmake

commit 0d7d868430b318454209942a997b1ad429e750c5
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 14:09:59 2025 -0500

    u

commit 3937cb1e764cb8949993a72419316ed715ecb74a
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 14:09:35 2025 -0500

    u

commit cddccf46b0a2931456e0429f55c8d27c5197bba1
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 14:04:51 2025 -0500

    u

commit 217d3fe67973ae27fe8860c617a3e12dba89fd04
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 14:03:59 2025 -0500

    u

commit 442230d922a803bdb8b63fb8529b1b557a7963dd
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 14:01:13 2025 -0500

    u

commit fb42e51ff07dd38d9a6a2585a82d0d6f32eb9a7c
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 13:59:03 2025 -0500

    u

commit 125dd3fc42996e3216a97c4d2e5e3e63779b306e
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 13:57:16 2025 -0500

    u

commit 4d5ecef3ed042895e7877ab101437f67253b559a
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 13:53:46 2025 -0500

    update

commit b2202368d55a5f3f83fbd72b76dae3ae2a97cfd8
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 13:46:14 2025 -0500

    Remove build

commit da0b838c00d87742f516d740f51ca3d226f0157c
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Tue Dec 9 13:40:22 2025 -0500

    Remove setup.py

commit 2fcb7f2944ece259a1d6138496bc8dbe322073c0
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 15:00:06 2025 -0500

    Meson build working offline.

commit bb5a5f18dfc27264c564d8d24fd4e1ace028a2e0
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 13:36:36 2025 -0500

    Add missing files

commit 95721a7e07b7c0d4573eeb31bc62e73e7ae5c854
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 13:27:41 2025 -0500

    Trying meson

commit 183849ca3a6d343dfe7571c0dce11af6b37e49c4
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 13:25:35 2025 -0500

    and 3.14

commit 01d40315b0bdcdad3643c412f5d3bf61e3eda6d7
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 13:24:43 2025 -0500

    Go back to linux

commit 63f687dc0ba666005fb14f420222a0d7a65edb92
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 13:24:33 2025 -0500

    Just 2 threads

commit 52777cda0480861b97a9b4fd5b4e922fdcdc76ee
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 13:02:32 2025 -0500

    Add -intel suffix

commit 677ba507994ed70a3996f69d7dd8d81a2b9e4b7f
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:57:25 2025 -0500

    Test macos-15 with py3.11

commit f59966bee636cdaf7cd543c3338e916f4b937c90
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:51:09 2025 -0500

    Try 3.12

commit 04d0e35d50a1d4011b93d30a9cdd4c2f9c16ad3c
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:43:48 2025 -0500

    Just test linux with py3.10

commit ccd232d916bcdeb84040db4a5c8cbd369d559fc1
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:32:19 2025 -0500

    Restore wheel testing

commit b28e52176850a74d36389714ea504f9eaa754738
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:28:28 2025 -0500

    Try matrix.exclude

commit 9a591fc04a4a775ff0221c12d5e6d1fdd69bd789
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:24:23 2025 -0500

    debug strategy matrix

commit c1555ededa158a5c626cf13e3c26688ec079a924
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:22:24 2025 -0500

    Add wildcard to build selector

commit 7c30736c53624241757ba0b0d91dc00f3c70ee37
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:14:17 2025 -0500

    Fix cibuildwheels options

commit 6cc1f98717af941d80e854d306c9e01d78997b06
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 12:05:14 2025 -0500

    Revise strategy matrix

commit d8550755815116521b7c834cf3866ddf5af4e233
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 11:57:14 2025 -0500

    Maybe don't setup python

commit 642424522aa4b42dd44bf249fac4014e7204c7fa
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 11:46:52 2025 -0500

    Fix oorb_data dependency

commit 6cfcc0f5b879fb9f193bc6b0c62e2fe2b30711bc
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 11:43:12 2025 -0500

    Move ephemeris data caching to separate workflow

commit dda55a392e6b580376546ad1ce3284889a1031f7
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 11:32:57 2025 -0500

    Fix archs location

commit 6399acf4b12d8cec8d244b58c7e9989f7a60a8c3
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 11:25:26 2025 -0500

    More caching work

commit 4124778dc460f7775f0cf2d8a68f1096b255cf0c
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 11:11:53 2025 -0500

    Accelerate testing.

commit 8275b8dc70e449a4f44adecfcd10765838548f1a
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Fri Dec 5 11:11:17 2025 -0500

    Use actions/cache for ephemeris data

commit fc23faf78aa595aaac5a0715c85ed2972e8acfaf
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Thu Dec 4 16:08:56 2025 -0500

    Fix typo

commit 693da791d5649aa6f88a20b16d8d313555bab01a
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Thu Dec 4 16:00:15 2025 -0500

    Streamline pypi workflow

commit 1752d19baa5a5673245349ffe639885644c5d5ef
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Thu Dec 4 14:38:58 2025 -0500

    Again, remove old python versions

commit e41c9957e14202795f091644c3b6f2863a279e6d
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Thu Dec 4 14:17:12 2025 -0500

    Rely on Makefile for copying the right ephemeris file; do not put temp files in artifact

commit 22ca586df2490f0a74852d17f849239ce209fd2f
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Thu Dec 4 12:52:25 2025 -0500

    And update CI actions versions

commit 77e1d4e5f5d787a25a0dfafda70ff2b606e163f1
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Thu Dec 4 12:51:01 2025 -0500

    Update actions versions

commit 26537fdd59a1c9b02787c5f7638b797851c5fb4f
Author: Michael S. P. Kelley <msk@astro.umd.edu>
Date:   Thu Dec 4 12:40:54 2025 -0500

    Use testpypi